use_frameworks!

platform :ios, '9.0'

target 'devtechieCircularView_Example' do
  pod 'devtechieCircularView', :path => '../'

  target 'devtechieCircularView_Tests' do
    inherit! :search_paths

    
  end
end
